export const FETCH_SCHOLARSHIP_APPLICATIONS = 'FETCH_SCHOLARSHIP_APPLICATIONS';
export const FILTER_SCHOLARSHIP_APPLICATIONS = 'FILTER_SCHOLARSHIP_APPLICATIONS';
export const VOTE_SCHOLARSHIP_APPLICATION = 'VOTE_SCHOLARSHIP_APPLICATION';
export const SORT_SCHOLARSHIP_APPLICATIONS = 'SORT_SCHOLARSHIP_APPLICATIONS';
